import pandas as pd
from utils.visualization import plot_distribution

# Load the combined dataset CSV
df = pd.read_csv("audio_paths_labeled.csv")  # Ensure this file is generated by pathsave.py

# Visualize the distribution of emotions across datasets
plot_distribution(df, title="Emotion Distribution Across Datasets")